version: 2.1

workflows:
  build-and-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/node:lts-browsers
    working_directory: ~/project/frontend
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Run tests
          command: |
            npm test